__title__ = 'MechanicalSoup'
__description__ = 'A Python library for automating interaction with websites'
__url__ = 'https://github.com/MechanicalSoup/MechanicalSoup'
__version__ = '0.8.0'
__license__ = 'MIT'
