__title__ = 'MechanicalSoup'
__description__ = 'A Python library for automating interaction with websites'
__url__ = 'https://mechanicalsoup.readthedocs.io/'
__github_url__ = 'https://github.com/MechanicalSoup/MechanicalSoup'
__version__ = '0.9.0-post4'
__license__ = 'MIT'
