name: Generate Combined Data

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at midnight daily
  workflow_dispatch:

jobs:
  generate_combined_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate combined data
        run: python process_revenue_data.py
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          FIRECRAWL_API_KEY: ${{ secrets.FIRECRAWL_API_KEY }}
